In [140]:
import pandas as pd

# Study Case 1: Mengolah Nilai Mahasiswa

## Case 1.1

In [141]:
data_nilai = {
    "Juchiro": 83.54,
    "Fandy": 86.79,
    "Erlangga": 88.57,
    "Matheos": 71.48,
    "Sugeng": 72.65,
    "Atma": 92.73,
    "Muliana": 83.22,
    "Iyya": 77.72,
    "Budiarto": 85.09,
    "Afendy": 88.98,
    "Muhaimin": 68.40,
}

data = pd.Series(data_nilai)
print(data)

Juchiro     83.54
Fandy       86.79
Erlangga    88.57
Matheos     71.48
Sugeng      72.65
Atma        92.73
Muliana     83.22
Iyya        77.72
Budiarto    85.09
Afendy      88.98
Muhaimin    68.40
dtype: float64

## Case 1.2

In [142]:
# print nilai Fandy
print(f"Nilai Fandy: {data['Fandy']:.2f}")

Nilai Fandy: 86.79

In [143]:
# print nilai Atma
print(f"Nilai Atma: {data['Atma']:.2f}")

Nilai Atma: 92.73

In [144]:
# print nilai Erlangga, Budiarto, Muhaimin
print(
    f"""
Nilai-nilai Erlangga, Budiarto, Muhaimin:
{data[['Erlangga', 'Budiarto', 'Muhaimin']]}
"""
)

Nilai-nilai Erlangga, Budiarto, Muhaimin:
Erlangga    88.57
Budiarto    85.09
Muhaimin    68.40
dtype: float64

## Case 1.3

In [145]:
if data.index.isin(["Yusril", "Priyo", "Yosua"]).any():
    pass
else:
    new_data_nilai = {"Yusril": 86.35, "Priyo": 74.73, "Yosua": 79.12}
    new_data = pd.Series(new_data_nilai)
    data = pd.concat([data, new_data])

print(data)

Juchiro     83.54
Fandy       86.79
Erlangga    88.57
Matheos     71.48
Sugeng      72.65
Atma        92.73
Muliana     83.22
Iyya        77.72
Budiarto    85.09
Afendy      88.98
Muhaimin    68.40
Yusril      86.35
Priyo       74.73
Yosua       79.12
dtype: float64

## Case 1.4

In [146]:
# ubah data Muliana menjadi 92.45
data["Muliana"] = 92.45

# ubah data Iyya
data["Iyya"] = 79.80

# ubah data Juchiro dan Fandy secara bersamaan
data[["Juchiro", "Fandy"]] = [90, 91]

print(data)

Juchiro     90.00
Fandy       91.00
Erlangga    88.57
Matheos     71.48
Sugeng      72.65
Atma        92.73
Muliana     92.45
Iyya        79.80
Budiarto    85.09
Afendy      88.98
Muhaimin    68.40
Yusril      86.35
Priyo       74.73
Yosua       79.12
dtype: float64

## Case 1.5

In [147]:
import os.path

# buat nama file
filename = "nilai_mahasiswa_update.csv"

if os.path.isfile(filename):
    pass
else:
    data.to_csv(filename)

## Exercise

1. Ubah nilai Afendy dan Sugeng masing-masing menjadi 85.5 dan 77.77

2. Ubah data nilai tersebut menjadi rentang 1-10

3. Hapus nilai Matheos dan Fandy

4. Export data menjadi data excel

In [148]:
# Ubah nilai Afendy dan Sugeng
data[["Afendy", "Sugeng"]] = [85.5, 77.77]
data

Juchiro     90.00
Fandy       91.00
Erlangga    88.57
Matheos     71.48
Sugeng      77.77
Atma        92.73
Muliana     92.45
Iyya        79.80
Budiarto    85.09
Afendy      85.50
Muhaimin    68.40
Yusril      86.35
Priyo       74.73
Yosua       79.12
dtype: float64

In [149]:
# Ubah data nilai jadi rentang 1-10
def normalize(value):
    return ((value - 0) / (100 - 0)) * (10 - 1) + 1


def isnormalized(series):
    return series.between(1, 10).all()


if isnormalized(data):
    pass
else:
    data = data.map(normalize)

data

Juchiro     9.1000
Fandy       9.1900
Erlangga    8.9713
Matheos     7.4332
Sugeng      7.9993
Atma        9.3457
Muliana     9.3205
Iyya        8.1820
Budiarto    8.6581
Afendy      8.6950
Muhaimin    7.1560
Yusril      8.7715
Priyo       7.7257
Yosua       8.1208
dtype: float64

In [150]:
# Hapus nilai Matheos and Fandy
if data.index.isin(["Matheos", "Fandy"]).any():
    data = data.drop(["Matheos", "Fandy"])
data

Juchiro     9.1000
Erlangga    8.9713
Sugeng      7.9993
Atma        9.3457
Muliana     9.3205
Iyya        8.1820
Budiarto    8.6581
Afendy      8.6950
Muhaimin    7.1560
Yusril      8.7715
Priyo       7.7257
Yosua       8.1208
dtype: float64

In [151]:
# export data menjadi data excel
import os.path

if os.path.isfile("mahasiswa.xlsx"):
    pass
else:
    with pd.ExcelWriter("mahasiswa.xlsx") as writer:
        data.to_excel(writer, sheet_name="nilai_mahasiswa_2025")

# Study Case 2: Data Pelanggan Mall

## Case 2.1

In [152]:
data = pd.read_csv("Mall_Customers.csv")
data

     CustomerID   Genre  Age  Annual_Income_(k$)  Spending_Score
0             1    Male   19                  15              39
1             2    Male   21                  15              81
2             3  Female   20                  16               6
3             4  Female   23                  16              77
4             5  Female   31                  17              40
..          ...     ...  ...                 ...             ...
195         196  Female   35                 120              79
196         197  Female   45                 126              28
197         198    Male   32                 126              74
198         199    Male   32                 137              18
199         200    Male   30                 137              83

[200 rows x 5 columns]

## Case 2.2

In [153]:
if "CustomerID" in data.columns:
    id_customer = data["CustomerID"].values + 1000
    data.index = id_customer

data

      CustomerID   Genre  Age  Annual_Income_(k$)  Spending_Score
1001           1    Male   19                  15              39
1002           2    Male   21                  15              81
1003           3  Female   20                  16               6
1004           4  Female   23                  16              77
1005           5  Female   31                  17              40
...          ...     ...  ...                 ...             ...
1196         196  Female   35                 120              79
1197         197  Female   45                 126              28
1198         198    Male   32                 126              74
1199         199    Male   32                 137              18
1200         200    Male   30                 137              83

[200 rows x 5 columns]

In [154]:
if "CustomerID" in data.columns:
    data = data.drop(["CustomerID"], axis=1)

data

       Genre  Age  Annual_Income_(k$)  Spending_Score
1001    Male   19                  15              39
1002    Male   21                  15              81
1003  Female   20                  16               6
1004  Female   23                  16              77
1005  Female   31                  17              40
...      ...  ...                 ...             ...
1196  Female   35                 120              79
1197  Female   45                 126              28
1198    Male   32                 126              74
1199    Male   32                 137              18
1200    Male   30                 137              83

[200 rows x 4 columns]

## Case 2.3

In [155]:
index_to_drop = []

if 1098 in data.index:
    index_to_drop.append(1098)

if 1099 in data.index:
    index_to_drop.append(1099)

data = data.drop(index_to_drop, axis=0)
print(data.loc[1095:1100])

       Genre  Age  Annual_Income_(k$)  Spending_Score
1095  Female   32                  60              42
1096    Male   24                  60              52
1097  Female   47                  60              47
1100    Male   20                  61              49

## Case 2.4

In [156]:
new_row = pd.DataFrame(
    {"Genre": "Male", "Age": 22, "Annual_Income_(k$)": 20, "Spending_Score": 83},
    index=[1201],
)
print(new_row)

     Genre  Age  Annual_Income_(k$)  Spending_Score
1201  Male   22                  20              83

In [157]:
data = pd.concat([data, new_row])

data

       Genre  Age  Annual_Income_(k$)  Spending_Score
1001    Male   19                  15              39
1002    Male   21                  15              81
1003  Female   20                  16               6
1004  Female   23                  16              77
1005  Female   31                  17              40
...      ...  ...                 ...             ...
1197  Female   45                 126              28
1198    Male   32                 126              74
1199    Male   32                 137              18
1200    Male   30                 137              83
1201    Male   22                  20              83

[199 rows x 4 columns]

## Case 2.5

In [158]:
# casting kolom Annual_Income_(k$)
data["Annual_Income_(k$)"] = data["Annual_Income_(k$)"].astype(float)

# casting kolom Spending_Score
data["Spending_Score"] = data["Spending_Score"].astype(float)

data.dtypes

Genre                  object
Age                     int64
Annual_Income_(k$)    float64
Spending_Score        float64
dtype: object

## Exercise

1. Ubah masing-masing header sesuai data berikut:

2. Tambah data berikut

3. Ubah umur data index 1200 menjadi 31 dan update data index 1002 menjadi

4. Export data menjadi data excel

In [159]:
# Ubah masing-masing header sesuai data berikut
data = data.rename(
    columns={
        "Genre": "JenisKelamin",
        "Age": "Umur",
        "Annual_Income_(k$)": "Pendapatan",
        "Spending_Score": "Skor",
    }
)
data

     JenisKelamin  Umur  Pendapatan  Skor
1001         Male    19        15.0  39.0
1002         Male    21        15.0  81.0
1003       Female    20        16.0   6.0
1004       Female    23        16.0  77.0
1005       Female    31        17.0  40.0
...           ...   ...         ...   ...
1197       Female    45       126.0  28.0
1198         Male    32       126.0  74.0
1199         Male    32       137.0  18.0
1200         Male    30       137.0  83.0
1201         Male    22        20.0  83.0

[199 rows x 4 columns]

In [160]:
row1 = pd.DataFrame(
    {"JenisKelamin": "Male", "Umur": 23, "Pendapatan": 100.5, "Skor": 50.4},
    index=[1202],
)
row2 = pd.DataFrame(
    {"JenisKelamin": "Female", "Umur": 45, "Pendapatan": 70.5, "Skor": 35.6},
    index=[1205],
)
row3 = pd.DataFrame(
    {"JenisKelamin": "Male", "Umur": 35, "Pendapatan": 88.3, "Skor": 54.8}, index=[1207]
)
data = pd.concat([data, row1, row2, row3])
data

     JenisKelamin  Umur  Pendapatan  Skor
1001         Male    19        15.0  39.0
1002         Male    21        15.0  81.0
1003       Female    20        16.0   6.0
1004       Female    23        16.0  77.0
1005       Female    31        17.0  40.0
...           ...   ...         ...   ...
1200         Male    30       137.0  83.0
1201         Male    22        20.0  83.0
1202         Male    23       100.5  50.4
1205       Female    45        70.5  35.6
1207         Male    35        88.3  54.8

[202 rows x 4 columns]

In [161]:
data.at[1200, "Umur"] = 31

data.loc[[1200], :]

     JenisKelamin  Umur  Pendapatan  Skor
1200         Male    31       137.0  83.0

In [162]:
data.loc[[1002], :] = pd.DataFrame(
    {"JenisKelamin": "Male", "Umur": 22, "Pendapatan": 20, "Skor": 83}, index=[1002]
)
data.loc[[1002], :]

     JenisKelamin  Umur  Pendapatan  Skor
1002         Male    22        20.0  83.0

In [163]:
with pd.ExcelWriter("mall_customer.xlsx") as writer:
    data.to_excel(writer, sheet_name="mall_customers_2025")

# Study Case 3: Data Pasien Rumah Sakit

## Case 3.1

In [164]:
dataA1 = pd.read_csv("patient_A1.csv")

dataA1

     Pregnancies  Glucose  BloodPressure  SkinThickness
0              6      148             72             35
1              1       85             66             29
2              8      183             64              0
3              1       89             66             23
4              0      137             40             35
..           ...      ...            ...            ...
167            4      120             68              0
168            4      110             66              0
169            3      111             90             12
170            6      102             82              0
171            6      134             70             23

[172 rows x 4 columns]

In [165]:
dataA2 = pd.read_csv("patient_A2.csv")

dataA2

     Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0          0  33.6                     0.627   50        1
1          0  26.6                     0.351   31        0
2          0  23.3                     0.672   32        1
3         94  28.1                     0.167   21        0
4        168  43.1                     2.288   33        1
..       ...   ...                       ...  ...      ...
167        0  29.6                     0.709   34        0
168        0  31.9                     0.471   29        0
169       78  28.4                     0.495   29        0
170        0  30.8                     0.180   36        1
171      130  35.4                     0.542   29        1

[172 rows x 5 columns]

In [166]:
dataB1 = pd.read_excel("patient.xlsx", sheet_name="patient_B1")

dataB1

     IdPatient  Pregnancies  SkinThickness   BMI  Age  Outcome
0          100            3              0   0.0   22        0
1          101            6              0  26.6   66        0
2          102            5              0  26.0   30        0
3          103            2             15  30.1   25        0
4          104            7             33  25.1   55        1
..         ...          ...            ...   ...  ...      ...
269        369           10             48  32.9   63        0
270        370            2             27  36.8   27        0
271        371            5             23  26.2   30        0
272        372            1              0  30.1   47        1
273        373            1             31  30.4   23        0

[274 rows x 6 columns]

In [167]:
dataB2 = pd.read_excel("patient.xlsx", sheet_name="patient_B2")

dataB2

     IdPatient  Glucose  BloodPressure  DiabetesPedigreeFunction
0          100       80              0                     0.174
1          101      166             74                     0.304
2          102      110             68                     0.292
3          103       81             72                     0.547
4          104      195             70                     0.163
..         ...      ...            ...                       ...
269        369      101             76                     0.171
270        370      122             70                     0.340
271        371      121             72                     0.245
272        372      126             60                     0.349
273        373       93             70                     0.315

[274 rows x 4 columns]

## Case 3.2

In [168]:
dataA = pd.concat([dataA1, dataA2], axis=1)
dataA

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
167,4,120,68,0,0,29.6,0.709,34,0
168,4,110,66,0,0,31.9,0.471,29,0
169,3,111,90,12,78,28.4,0.495,29,0
170,6,102,82,0,0,30.8,0.180,36,1
171,6,134,70,23,130,35.4,0.542,29,1

In [169]:
dataB = dataB1.merge(dataB2, on="IdPatient")

dataB

,IdPatient,Pregnancies,SkinThickness,BMI,Age,Outcome,Glucose,BloodPressure,DiabetesPedigreeFunction
0,100,3,0,0.0,22,0,80,0,0.174
1,101,6,0,26.6,66,0,166,74,0.304
2,102,5,0,26.0,30,0,110,68,0.292
3,103,2,15,30.1,25,0,81,72,0.547
4,104,7,33,25.1,55,1,195,70,0.163
...,...,...,...,...,...,...,...,...,...
269,369,10,48,32.9,63,0,101,76,0.171
270,370,2,27,36.8,27,0,122,70,0.340
271,371,5,23,26.2,30,0,121,72,0.245
272,372,1,0,30.1,47,1,126,60,0.349
273,373,1,31,30.4,23,0,93,70,0.315

In [170]:
dataB = dataB.drop("IdPatient", axis=1)

data_whole = pd.concat([dataA, dataB], ignore_index=True)

data_whole

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0.0,33.6,0.627,50,1
1,1,85,66,29,0.0,26.6,0.351,31,0
2,8,183,64,0,0.0,23.3,0.672,32,1
3,1,89,66,23,94.0,28.1,0.167,21,0
4,0,137,40,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
441,10,101,76,48,NaN,32.9,0.171,63,0
442,2,122,70,27,NaN,36.8,0.340,27,0
443,5,121,72,23,NaN,26.2,0.245,30,0
444,1,126,60,0,NaN,30.1,0.349,47,1
445,1,93,70,31,NaN,30.4,0.315,23,0

## Case 3.3

In [171]:
# drop data Pregnancies, DiabetesPedigreeFunction, and Outcome

data_whole = data_whole.drop(
    ["Pregnancies", "DiabetesPedigreeFunction", "Outcome"], axis=1
)

data_whole

     Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age
0        148             72             35      0.0  33.6   50
1         85             66             29      0.0  26.6   31
2        183             64              0      0.0  23.3   32
3         89             66             23     94.0  28.1   21
4        137             40             35    168.0  43.1   33
..       ...            ...            ...      ...   ...  ...
441      101             76             48      NaN  32.9   63
442      122             70             27      NaN  36.8   27
443      121             72             23      NaN  26.2   30
444      126             60              0      NaN  30.1   47
445       93             70             31      NaN  30.4   23

[446 rows x 6 columns]

## Case 3.4

In [172]:
data_whole[:10][["Glucose", "BloodPressure", "Age"]]

   Glucose  BloodPressure  Age
0      148             72   50
1       85             66   31
2      183             64   32
3       89             66   21
4      137             40   33
5      116             74   30
6       78             50   26
7      115              0   29
8      197             70   53
9      125             96   54

## Exercise

1. Tampilkan data pada urutan ke 100 hingga 107 untuk data insulin dan BMI

2. Hapus 5 data terakhir

3. Ekspor data menjadi dua file:

   - File pertama berisi semua data kolom dan ekspor ke file csv
   - File kedua hanya berisi data BMI dan Age ke file excel

In [173]:
# 1st exercise

data_whole[100:108][["Insulin", "BMI"]]

     Insulin   BMI
100      0.0  39.0
101      0.0  26.1
102      0.0  22.5
103     40.0  26.6
104      0.0  39.6
105    152.0  28.7
106      0.0  22.4
107    140.0  29.5

In [174]:
# 2nd exercise

data_whole = data_whole.drop(data_whole.tail(5).index)

data_whole

     Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age
0        148             72             35      0.0  33.6   50
1         85             66             29      0.0  26.6   31
2        183             64              0      0.0  23.3   32
3         89             66             23     94.0  28.1   21
4        137             40             35    168.0  43.1   33
..       ...            ...            ...      ...   ...  ...
436      106             76              0      NaN  37.5   26
437      190             92              0      NaN  35.5   66
438       88             58             26      NaN  28.4   22
439      170             74             31      NaN  44.0   43
440       89             62              0      NaN  22.5   33

[441 rows x 6 columns]

In [175]:
data_whole.to_csv("patient_whole.csv")

In [176]:
with pd.ExcelWriter("patient_bmi_age.xlsx") as writer:
    data_whole[["BMI", "Age"]].to_excel(writer, sheet_name="patients")

# Study Case 4: Accessing Database

In [178]:
import sqlite3 as sql

In [179]:
con = sql.connect("chinook.db")

In [180]:
invoice = pd.read_sql("select * from invoices", con)

invoice

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [183]:
# akses data customer yang telah memiliki invoice
query = """
select * from invoices
join customers using (CustomerId)
"""

customer_with_invoices = pd.read_sql(query, con)

customer_with_invoices

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,FirstName,...,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,98,1,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,Luís,...,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,121,1,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,Luís,...,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,143,1,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94,Luís,...,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
3,195,1,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99,Luís,...,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
4,316,1,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98,Luís,...,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,45,59,2009-07-08 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,5.94,Puja,...,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
408,97,59,2010-02-26 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.99,Puja,...,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
409,218,59,2011-08-20 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,1.98,Puja,...,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
410,229,59,2011-09-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,13.86,Puja,...,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
411,284,59,2012-05-30 00:00:00,"3,Raj Bhavan Road",Bangalore,None,India,560001,8.91,Puja,...,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3