# Studi Case 1: Akses Data Penumpang Kapal

In [173]:
import pandas as pd

In [174]:
titanic_data = pd.read_csv("titanic.csv")

titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Case 1.1

In [175]:
# tampilkan 10 penumpang teratas

titanic_data[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## Case 1.2

In [176]:
# tampilkan informasi nama, umur, tiket, dan fare dari 10 penumpang terakhir

titanic_data[-10:][["Name", "Ticket", "Age", "Fare"]]

                                         Name            Ticket   Age     Fare
881                        Markun, Mr. Johann            349257  33.0   7.8958
882              Dahlberg, Miss. Gerda Ulrika              7552  22.0  10.5167
883             Banfield, Mr. Frederick James  C.A./SOTON 34068  28.0  10.5000
884                    Sutehall, Mr. Henry Jr   SOTON/OQ 392076  25.0   7.0500
885      Rice, Mrs. William (Margaret Norton)            382652  39.0  29.1250
886                     Montvila, Rev. Juozas            211536  27.0  13.0000
887              Graham, Miss. Margaret Edith            112053  19.0  30.0000
888  Johnston, Miss. Catherine Helen "Carrie"        W./C. 6607   NaN  23.4500
889                     Behr, Mr. Karl Howell            111369  26.0  30.0000
890                       Dooley, Mr. Patrick            370376  32.0   7.7500

## Case 1.3

In [177]:
# tampilkan informasi survived hingga ticket

titanic_data = titanic_data.reset_index()
titanic_data = titanic_data.set_index("Name")

titanic_data.loc[
    ["Braund, Mr. Owen Harris", "Heikkinen, Miss. Laina", "Markun, Mr. Johann"],
    "PassengerId":"Ticket",
]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket
Name,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282
"Markun, Mr. Johann",882,0,3,male,33.0,0,0,349257

## Case 1.4

In [178]:
# tampilkan informasi age, ticket, dan embarked dari penumpang berikut

titanic_data.loc[
    "Heikkinen, Miss. Laina":"Palsson, Master. Gosta Leonard",
    ["Age", "Ticket", "Embarked"],
]

                                               Age            Ticket Embarked
Name
Heikkinen, Miss. Laina                        26.0  STON/O2. 3101282        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0            113803        S
Allen, Mr. William Henry                      35.0            373450        S
Moran, Mr. James                               NaN            330877        Q
McCarthy, Mr. Timothy J                       54.0             17463        S
Palsson, Master. Gosta Leonard                 2.0            349909        S

## Exercise

1. Ubah index menjadi kolom passangerId tanpa menghilangkan kolom nama
2. Tamplikan data penumpang yang memiliki id 29, 78, 66
3. Tampilkan informasi penumpang id 40-50 dan tampilkan kolom name, sibsp, parch
4. Tampilkan informasi ticket dari penumpang dengan id 887
5. Kembalikan index ke bentuk default

In [179]:
# Ubah index menjadi kolom passangerId

titanic_data = titanic_data.reset_index()
titanic_data.set_index(["Name", "PassengerId"], inplace=True, drop=True)

titanic_data

,,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,PassengerId,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,3,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,4,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,887,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,889,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [180]:
# tampilkan data penumpang yang memiliki id 29, 78, 66

idx = pd.IndexSlice
titanic_data.loc[idx[:, [29, 78, 66]], :]

,,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,PassengerId,,,,,,,,,,,
"O'Dwyer, Miss. Ellen ""Nellie""",29,28,1,3,female,NaN,0,0,330959,7.8792,NaN,Q
"Moutal, Mr. Rahamin Haim",78,77,0,3,male,NaN,0,0,374746,8.0500,NaN,S
"Moubarek, Master. Gerios",66,65,1,3,male,NaN,1,1,2661,15.2458,NaN,C

In [181]:
# Tampilkan informasi penumpang id 40-50 dan tampilkan kolom name, sibsp, parch
titanic_data[40:50][["SibSp", "Parch"]]

                                                                SibSp  Parch
Name                                               PassengerId
Ahlin, Mrs. Johan (Johanna Persdotter Larsson)     41               1      0
Turpin, Mrs. William John Robert (Dorothy Ann W... 42               1      0
Kraeff, Mr. Theodor                                43               0      0
Laroche, Miss. Simonne Marie Anne Andree           44               1      2
Devaney, Miss. Margaret Delia                      45               0      0
Rogers, Mr. William John                           46               0      0
Lennon, Mr. Denis                                  47               1      0
O'Driscoll, Miss. Bridget                          48               0      0
Samaan, Mr. Youssef                                49               2      0
Arnold-Franchi, Mrs. Josef (Josefine Franchi)      50               1      0

In [182]:
# tampilkan inforamsi ticket dari penumpang dengan id 887

titanic_data.loc[(slice(None), 887), "Ticket"]

Name                   PassengerId
Montvila, Rev. Juozas  887            211536
Name: Ticket, dtype: object

In [183]:
# kembalikan i ndex ke bentuk default

titanic_data = titanic_data.reset_index()

titanic_data

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,4,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,889,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

# Study Case 2: Akses Data Penumpang Kapal (2)

## Case 2.1

In [184]:
cond = titanic_data["Sex"] == "female"

titanic_data.loc[cond]

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,3,1,1,female,35.0,1,0,113803,53.1000,C123,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,8,1,3,female,27.0,0,2,347742,11.1333,NaN,S
9,"Nasser, Mrs. Nicholas (Adele Achem)",10,9,1,2,female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,"Shelley, Mrs. William (Imanita Parrish Hall)",881,880,1,2,female,25.0,0,1,230433,26.0000,NaN,S
882,"Dahlberg, Miss. Gerda Ulrika",883,882,0,3,female,22.0,0,0,7552,10.5167,NaN,S
885,"Rice, Mrs. William (Margaret Norton)",886,885,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
887,"Graham, Miss. Margaret Edith",888,887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S

##  Case 2.2

In [185]:
# penumpang yang memiliki usia di atas 40 tahun

age_condition = titanic_data["Age"] > 40

titanic_data[age_condition][["Name", "Age", "Pclass", "Fare"]]

                                                  Name   Age  Pclass     Fare
6                              McCarthy, Mr. Timothy J  54.0       1  51.8625
11                            Bonnell, Miss. Elizabeth  58.0       1  26.5500
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0       2  16.0000
33                               Wheadon, Mr. Edward H  66.0       2  10.5000
35                      Holverson, Mr. Alexander Oskar  42.0       1  52.0000
..                                                 ...   ...     ...      ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0       1  25.9292
865                           Bystrom, Mrs. (Karolina)  42.0       2  13.0000
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1  52.5542
873                        Vander Cruyssen, Mr. Victor  47.0       3   9.0000
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1  83.1583

[150 rows x 4 columns]

## Case 2.3

In [186]:
# tampilkan data penumpang yang harga tiketnya di atas $50 dan berangkat dari port Southampton

fare_cond = titanic_data["Fare"] > 50
port_cond = titanic_data["Embarked"] == "S"

titanic_data[fare_cond & port_cond]

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,3,1,1,female,35.0,1,0,113803,53.1000,C123,S
6,"McCarthy, Mr. Timothy J",7,6,0,1,male,54.0,0,0,17463,51.8625,E46,S
27,"Fortune, Mr. Charles Alexander",28,27,0,1,male,19.0,3,2,19950,263.0000,C23 C25 C27,S
35,"Holverson, Mr. Alexander Oskar",36,35,0,1,male,42.0,1,0,113789,52.0000,NaN,S
62,"Harris, Mr. Henry Birkhardt",63,62,0,1,male,45.0,1,0,36973,83.4750,C83,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,"Sage, Mr. Douglas Bullen",847,846,0,3,male,NaN,8,2,CA. 2343,69.5500,NaN,S
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",857,856,1,1,female,45.0,1,1,36928,164.8667,NaN,S
863,"Sage, Miss. Dorothy Edith ""Dolly""",864,863,0,3,female,NaN,8,2,CA. 2343,69.5500,NaN,S
867,"Roebling, Mr. Washington Augustus II",868,867,0,1,male,31.0,0,0,PC 17590,50.4958,A24,S
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,871,1,1,female,47.0,1,1,11751,52.5542,D35,S

## Case 2.4

In [187]:
# Tampilkan informasi Name, Embarked, SibSp dan Parch dari  penumpang yang SibSp-nya lebih dari 6 atau Parch lebih dari 2

sibsp_cond = titanic_data["SibSp"] > 6
parch_cond = titanic_data["Parch"] > 2

titanic_data[sibsp_cond | parch_cond][["Name", "Embarked", "SibSp", "Parch"]]

                                                  Name Embarked  SibSp  Parch
13                         Andersson, Mr. Anders Johan        S      1      5
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...        S      1      5
86                              Ford, Mr. William Neal        S      1      3
159                         Sage, Master. Thomas Henry        S      8      2
167    Skoog, Mrs. William (Anna Bernhardina Karlsson)        S      1      4
180                       Sage, Miss. Constance Gladys        S      8      2
201                                Sage, Mr. Frederick        S      8      2
324                           Sage, Mr. George John Jr        S      8      2
360                                 Skoog, Mr. Wilhelm        S      1      4
437              Richards, Mrs. Sidney (Emily Hocking)        S      2      3
438                                  Fortune, Mr. Mark        S      1      4
567        Palsson, Mrs. Nils (Alma Cornelia Berglund)        S      0      4
610  Andersson, Mrs. Anders Johan (Alfrida Konstant...        S      1      5
638             Panula, Mrs. Juha (Maria Emilia Ojala)        S      0      5
678            Goodwin, Mrs. Frederick (Augusta Tyler)        S      1      6
736            Ford, Mrs. Edward (Margaret Ann Watson)        S      1      3
774              Hocking, Mrs. Elizabeth (Eliza Needs)        S      1      3
792                            Sage, Miss. Stella Anna        S      8      2
846                           Sage, Mr. Douglas Bullen        S      8      2
858              Baclini, Mrs. Solomon (Latifa Qurban)        C      0      3
863                  Sage, Miss. Dorothy Edith "Dolly"        S      8      2
885               Rice, Mrs. William (Margaret Norton)        Q      0      5

## Exercise

1. Tampilkan nama dan gender penumpang yang survived dan memiliki  usia dibawah 25 tahun.
2. Tampilkan data penumpang yang survived dan berangkat dari port Queenstown atau Southampton
3. Tampilkan data penumpang yang jumlah anggota keluarganya lebih dari 7
4. Tampilkan data penumpang yang tidak survived, memiliki anggota keluarga lebih dari 5 dan tidak berangkat dari port Queenstown

In [188]:
# Tampilkan nama dan gender penumpang yang survived dan memiliki  usia dibawah 25 tahun.

surv_cond = titanic_data["Survived"] == 1
age_cond = titanic_data["Age"] < 25

titanic_data[surv_cond & age_cond][["Name", "Sex"]]

                                         Name     Sex
9         Nasser, Mrs. Nicholas (Adele Achem)  female
10            Sandstrom, Miss. Marguerite Rut  female
22                McGowan, Miss. Anna "Annie"  female
39                Nicola-Yarred, Miss. Jamila  female
43   Laroche, Miss. Simonne Marie Anne Andree  female
..                                        ...     ...
855                Aks, Mrs. Sam (Leah Rosen)  female
858     Baclini, Mrs. Solomon (Latifa Qurban)  female
869           Johnson, Master. Harold Theodor    male
875          Najib, Miss. Adele Kiamie "Jane"  female
887              Graham, Miss. Margaret Edith  female

[118 rows x 2 columns]

In [189]:
# Tampilkan data penumpang yang survived dan berangkat dari port Queenstown atau Southampton

surv_cond = titanic_data["Survived"] == 1
port_queenstown_cond = titanic_data["Embarked"] == "Q"
port_southampton_cond = titanic_data["Embarked"] == "S"

titanic_data[surv_cond & (port_queenstown_cond | port_southampton_cond)]

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,"Heikkinen, Miss. Laina",3,2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,3,1,1,female,35.0,1,0,113803,53.1000,C123,S
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,8,1,3,female,27.0,0,2,347742,11.1333,NaN,S
10,"Sandstrom, Miss. Marguerite Rut",11,10,1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
11,"Bonnell, Miss. Elizabeth",12,11,1,1,female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,"Bystrom, Mrs. (Karolina)",866,865,1,2,female,42.0,0,0,236852,13.0000,NaN,S
869,"Johnson, Master. Harold Theodor",870,869,1,3,male,4.0,1,1,347742,11.1333,NaN,S
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,871,1,1,female,47.0,1,1,11751,52.5542,D35,S
880,"Shelley, Mrs. William (Imanita Parrish Hall)",881,880,1,2,female,25.0,0,1,230433,26.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,887,1,1,female,19.0,0,0,112053,30.0000,B42,S

In [190]:
# Tampilkan data penumpang yang jumlah anggota keluarganya lebih dari 7

titanic_data["FamSize"] = titanic_data["SibSp"] + titanic_data["Parch"]
total_fam_cond = titanic_data["FamSize"] > 7

titanic_data[total_fam_cond]

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamSize
159,"Sage, Master. Thomas Henry",160,159,0,3,male,NaN,8,2,CA. 2343,69.55,NaN,S,10
180,"Sage, Miss. Constance Gladys",181,180,0,3,female,NaN,8,2,CA. 2343,69.55,NaN,S,10
201,"Sage, Mr. Frederick",202,201,0,3,male,NaN,8,2,CA. 2343,69.55,NaN,S,10
324,"Sage, Mr. George John Jr",325,324,0,3,male,NaN,8,2,CA. 2343,69.55,NaN,S,10
792,"Sage, Miss. Stella Anna",793,792,0,3,female,NaN,8,2,CA. 2343,69.55,NaN,S,10
846,"Sage, Mr. Douglas Bullen",847,846,0,3,male,NaN,8,2,CA. 2343,69.55,NaN,S,10
863,"Sage, Miss. Dorothy Edith ""Dolly""",864,863,0,3,female,NaN,8,2,CA. 2343,69.55,NaN,S,10

In [191]:
# Tampilkan data penumpang yang tidak survived, memiliki anggota keluarga lebih dari 5 dan tidak berangkat dari port Queenstown

surv_cond = titanic_data["Survived"] == 0
total_fam_cond = titanic_data["FamSize"] > 5
port_cond = titanic_data["Embarked"] != "Q"

titanic_data[surv_cond & total_fam_cond & port_cond]

,Name,PassengerId,index,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamSize
13,"Andersson, Mr. Anders Johan",14,13,0,3,male,39.0,1,5,347082,31.2750,NaN,S,6
59,"Goodwin, Master. William Frederick",60,59,0,3,male,11.0,5,2,CA 2144,46.9000,NaN,S,7
71,"Goodwin, Miss. Lillian Amy",72,71,0,3,female,16.0,5,2,CA 2144,46.9000,NaN,S,7
119,"Andersson, Miss. Ellis Anna Maria",120,119,0,3,female,2.0,4,2,347082,31.2750,NaN,S,6
159,"Sage, Master. Thomas Henry",160,159,0,3,male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
180,"Sage, Miss. Constance Gladys",181,180,0,3,female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
182,"Asplund, Master. Clarence Gustaf Hugo",183,182,0,3,male,9.0,4,2,347077,31.3875,NaN,S,6
201,"Sage, Mr. Frederick",202,201,0,3,male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
324,"Sage, Mr. George John Jr",325,324,0,3,male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
386,"Goodwin, Master. Sidney Leonard",387,386,0,3,male,1.0,5,2,CA 2144,46.9000,NaN,S,7
480,"Goodwin, Master. Harold Victor",481,480,0,3,male,9.0,5,2,CA 2144,46.9000,NaN,S,7
541,"Andersson, Miss. Ingeborg Constanzia",542,541,0,3,female,9.0,4,2,347082,31.2750,NaN,S,6
542,"Andersson, Miss. Sigrid Elisabeth",543,542,0,3,female,11.0,4,2,347082,31.2750,NaN,S,6
610,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",611,610,0,3,female,39.0,1,5,347082,31.2750,NaN,S,6
678,"Goodwin, Mrs. Frederick (Augusta Tyler)",679,678,0,3,female,43.0,1,6,CA 2144,46.9000,NaN,S,7
683,"Goodwin, Mr. Charles Edward",684,683,0,3,male,14.0,5,2,CA 2144,46.9000,NaN,S,7
792,"Sage, Miss. Stella Anna",793,792,0,3,female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
813,"Andersson, Miss. Ebba Iris Alfrida",814,813,0,3,female,6.0,4,2,347082,31.2750,NaN,S,6
846,"Sage, Mr. Douglas Bullen",847,846,0,3,male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
850,"Andersson, Master. Sigvard Harald Elias",851,850,0,3,male,4.0,4,2,347082,31.2750,NaN,S,6
863,"Sage, Miss. Dorothy Edith ""Dolly""",864,863,0,3,female,NaN,8,2,CA. 2343,69.5500,NaN,S,10

# Study Case 3: Analisis Karakter di Film

In [192]:
lotr = pd.read_csv("WordsByCharacter.csv")

lotr.head()

,Film,Chapter,Character,Race,Words
0,The Fellowship Of The Ring,01: Prologue,Bilbo,Hobbit,4
1,The Fellowship Of The Ring,01: Prologue,Elrond,Elf,5
2,The Fellowship Of The Ring,01: Prologue,Galadriel,Elf,460
3,The Fellowship Of The Ring,01: Prologue,Gollum,Gollum,20
4,The Fellowship Of The Ring,02: Concerning Hobbits,Bilbo,Hobbit,214

## Case 3.1

In [193]:
# Siapa saja karakter yang berbicara pada chapter pertama "The Fellowship of the Ring?"

talk_cond = lotr["Words"] > 0
movie_cond = lotr["Film"].str.contains("Fellowship")
chapter_cond = lotr["Chapter"] == "01: Prologue"

lotr[movie_cond & chapter_cond]

                         Film       Chapter  Character    Race  Words
0  The Fellowship Of The Ring  01: Prologue      Bilbo  Hobbit      4
1  The Fellowship Of The Ring  01: Prologue     Elrond     Elf      5
2  The Fellowship Of The Ring  01: Prologue  Galadriel     Elf    460
3  The Fellowship Of The Ring  01: Prologue     Gollum  Gollum     20

In [194]:
multi = lotr.set_index(["Film", "Chapter", "Race", "Character"])

multi

                                                                    Words
Film                       Chapter                Race   Character
The Fellowship Of The Ring 01: Prologue           Hobbit Bilbo          4
                                                  Elf    Elrond         5
                                                         Galadriel    460
                                                  Gollum Gollum        20
                           02: Concerning Hobbits Hobbit Bilbo        214
...                                                                   ...
The Return Of The King     76: The Grey Havens    Elf    Elrond         6
                                                  Hobbit Frodo        132
                                                  Elf    Galadriel     17
                                                  Ainur  Gandalf       42
                                                  Hobbit Sam           14

[731 rows x 1 columns]

In [195]:
multi.loc[("The Fellowship Of The Ring", "01: Prologue"), :]

/var/folders/34/_j3kcpxd38lfbdvtp0clnhrw0000gn/T/ipykernel_58826/1064222838.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  multi.loc[("The Fellowship Of The Ring", "01: Prologue"), :]

                  Words
Race   Character
Hobbit Bilbo          4
Elf    Elrond         5
       Galadriel    460
Gollum Gollum        20

## Case 3.2

In [196]:
# Siapa tiga elf pertama yang berbicara pada film "The Fellowship of the Ring"?

elf_cond = lotr["Race"] == "Elf"
film_cond = lotr["Film"] == "The Fellowship Of The Ring"

lotr[elf_cond & film_cond].set_index(["Film", "Chapter", "Race", "Character"]).head(3)

                                                                  Words
Film                       Chapter                Race Character
The Fellowship Of The Ring 01: Prologue           Elf  Elrond         5
                                                       Galadriel    460
                           21: Flight To The Ford Elf  Arwen        131

## Case 3.3

In [197]:
# Seberapa banyak Gandalf dan Saruman berbicara dalam tiap chapter di "The Two Towers"

multi.loc[("The Two Towers", slice(None), slice(None), ["Gandalf", "Saruman"]), :]

                                                                                  Words
Film           Chapter                                           Race  Character
The Two Towers 01: The Foundations Of Stone                      Ainur Gandalf       39
               15: The White Rider                               Ainur Gandalf      298
               17: The Heir Of Númenor                           Ainur Gandalf      226
               20: The King Of The Golden Hall                   Ainur Gandalf      151
               22: Simbelmynë on the Burial Mounds               Ainur Gandalf       28
               23: The King's Decision                           Ainur Gandalf      165
               58: Forth Eorlingas                               Ainur Gandalf       21
               65: The Battle For Middle Earth Is About To Begin Ainur Gandalf       36
               06: The Burning of the Westfold                   Ainur Saruman      187
               25: The Ring Of Barahir                           Ainur Saruman       68
               27: Exodus From Edoras                            Ainur Saruman        4
               36: Isengard Unleashed                            Ainur Saruman       50

## Case 3.4

In [198]:
# Berapa banyak Isildur berbicara dalam semua film?

multi.loc[(slice(None), slice(None), slice(None), "Isildur"), :]

                                                                    Words
Film                       Chapter                  Race Character
The Fellowship Of The Ring 24: The Fate Of The Ring Men  Isildur        1

## Exercise

1. Siapakah karakter yang berbicara pada chapter 03: The Shire pada "The Fellowship of the Ring"
2. Berapa kali Gollum berbicara untuk tiap chapter pada "The Return Of The King".

In [201]:
# Siapakah karakter yang berbicara pada chapter 03: The Shire pada "The Fellowship of the Ring"

chapter_cond = lotr["Chapter"] == "03: The Shire"
film_cond = lotr["Film"] == "The Fellowship Of The Ring"

lotr[chapter_cond & film_cond]

                         Film        Chapter    Character    Race  Words
5  The Fellowship Of The Ring  03: The Shire        Bilbo  Hobbit     70
6  The Fellowship Of The Ring  03: The Shire        Frodo  Hobbit    128
7  The Fellowship Of The Ring  03: The Shire      Gandalf   Ainur    197
8  The Fellowship Of The Ring  03: The Shire  Hobbit Kids  Hobbit     10
9  The Fellowship Of The Ring  03: The Shire      Hobbits  Hobbit     12

In [200]:
# Berapa kali Gollum berbicara untuk tiap chapter pada "The Return Of The King".

char_cond = lotr["Character"] == "Gollum"
film_cond = lotr["Film"] == "The Return Of The King"

lotr[char_cond & film_cond]

,Film,Chapter,Character,Race,Words
464,The Return Of The King,01: The Finding Of The Ring,Gollum,Gollum,3
467,The Return Of The King,02: Journey To The Cross-roads,Gollum,Gollum,41
491,The Return Of The King,06: Gollum's Villany,Gollum,Gollum,149
512,The Return Of The King,13: Cross-roads Of The Fallen King,Gollum,Gollum,13
519,The Return Of The King,15: Minas Morgul,Gollum,Gollum,50
522,The Return Of The King,16: Sam's Warning,Gollum,Gollum,13
551,The Return Of The King,23: The Stairs Of Cirith Ungol,Gollum,Gollum,76
563,The Return Of The King,27: The Parting Of Sam & Frodo,Gollum,Gollum,79
617,The Return Of The King,38: Shelob's Lair,Gollum,Gollum,64
705,The Return Of The King,68: Mount Doom,Gollum,Gollum,17
709,The Return Of The King,70: The Crack Of Doom,Gollum,Gollum,5