In [3]:
import pandas as pd
import numpy as np

# Test .agg()

In [6]:
df = pd.DataFrame(
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [np.nan, np.nan, np.nan]],
    columns=['A', 'B', 'C']
)
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [5]:
df.agg(['sum', 'min'])

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [7]:
df.agg({'A': ['sum', 'min'], 'B': ['min', 'max']})

        A    B
sum  12.0  NaN
min   1.0  2.0
max   NaN  8.0

# Test pd.cut()

In [8]:
sorted_recency = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
quantiles = sorted_recency.quantile([0.2, 0.4, 0.6, 0.8]).tolist()
labels = ["Group 1", "Group 2", "Group 3", "Group 4", "Group 5"]
sorted_recency_groups = pd.cut(
    sorted_recency, 
    bins=[-float("inf")] + quantiles + [float("inf")], 
    labels=labels
)
print(sorted_recency_groups)

0    Group 1
1    Group 1
2    Group 2
3    Group 2
4    Group 3
5    Group 3
6    Group 4
7    Group 4
8    Group 5
9    Group 5
dtype: category
Categories (5, object): ['Group 1' < 'Group 2' < 'Group 3' < 'Group 4' < 'Group 5']

# Test pd.pivot_table()

In [10]:
df = pd.DataFrame(
    {
        "A": ["foo", "foo", "foo", "foo", "foo","bar", "bar", "bar", "bar"],
        "B": ["one", "one", "one", "two", "two","one", "one", "two", "two"],
        "C": ["small", "large", "large", "small", "small", "large", "small", "small","large"],
        "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
        "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]
    }
)
df

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [14]:
pd.pivot_table(df, values=['D','E'], index=['A', 'B'], columns=['C'], aggfunc='sum')

            D           E
C       large small large small
A   B
bar one   4.0   5.0   6.0   8.0
    two   7.0   6.0   9.0   9.0
foo one   4.0   1.0   9.0   2.0
    two   NaN   6.0   NaN  11.0

In [13]:
pd.pivot_table(
    df, 
    values='D', 
    index=['A', 'B'], 
    columns=['C'], 
    aggfunc='sum',
    fill_value=0
)

C        large  small
A   B
bar one      4      5
    two      7      6
foo one      4      1
    two      0      6

In [16]:
pd.pivot_table(
    df, 
    values=['D','E'], 
    index=['A','C'],
    aggfunc={
        'D': 'mean',
        'E': ['min', 'max','mean']
    }
)

                  D   E
               mean max      mean min
A   C
bar large  5.500000   9  7.500000   6
    small  5.500000   9  8.500000   8
foo large  2.000000   5  4.500000   4
    small  2.333333   6  4.333333   2