In [1]:
import pandas as pd

In [2]:
string_data = pd.Series(["aardvark", None, None,  "avocado"])

string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [3]:
float_data = pd.Series([1, 2, None], dtype='float64')

float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [5]:
float_data[float_data.notna()]

0    1.0
1    2.0
dtype: float64

In [7]:
float_data2 = pd.DataFrame([[1., 6.5, 3.], [1., None, None],[None, None, None], [None, 6.5, 3.]], dtype=float)

float_data2

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
float_data2.dropna()

     0    1    2
0  1.0  6.5  3.0

In [9]:
float_data2.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
float_data2.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]