In [2]:
import pandas as pd

In [7]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [8]:
frame2 = pd.DataFrame(data, columns=["year", "pop", "state", "debt"])

frame2

   year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nevada  NaN
4  2002  2.9  Nevada  NaN
5  2003  3.2  Nevada  NaN

In [9]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [10]:
frame2.debt

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: debt, dtype: object

In [11]:
frame2.loc[1]

year     2001
pop       1.7
state    Ohio
debt      NaN
Name: 1, dtype: object

In [12]:
frame2.iloc[2]

year     2002
pop       3.6
state    Ohio
debt      NaN
Name: 2, dtype: object

In [14]:
frame2.debt = 16.5

frame2

   year  pop   state  debt
0  2000  1.5    Ohio  16.5
1  2001  1.7    Ohio  16.5
2  2002  3.6    Ohio  16.5
3  2001  2.4  Nevada  16.5
4  2002  2.9  Nevada  16.5
5  2003  3.2  Nevada  16.5

In [15]:
# trying to delete multiple columns

# define column names
col_names = ["eastern", "western", "southern", "northern"]

# create new columns

for col in col_names:
    frame2[col] = None

frame2

   year  pop   state  debt eastern western southern northern
0  2000  1.5    Ohio  16.5    None    None     None     None
1  2001  1.7    Ohio  16.5    None    None     None     None
2  2002  3.6    Ohio  16.5    None    None     None     None
3  2001  2.4  Nevada  16.5    None    None     None     None
4  2002  2.9  Nevada  16.5    None    None     None     None
5  2003  3.2  Nevada  16.5    None    None     None     None

In [16]:
# delete the column names

for col in col_names:
    del frame2[col]

frame2

   year  pop   state  debt
0  2000  1.5    Ohio  16.5
1  2001  1.7    Ohio  16.5
2  2002  3.6    Ohio  16.5
3  2001  2.4  Nevada  16.5
4  2002  2.9  Nevada  16.5
5  2003  3.2  Nevada  16.5

In [17]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}

frame3  = pd.DataFrame(populations)

frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [18]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [19]:
frame3.T.T

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
ars